customhost = "database-1.cd9sogco3up8.us-east-1.rds.amazonaws.com"
customuser = "vaiibhavkale"
custompass = "vaiibhavkale"
customdb = "employee"
custombucket = "addemployee0321"
customregion = "us-east-1"
